### PR TITLE
customize require

### PR DESCRIPTION
**Pull request by hzjzx**
customize require for environment such as electron

### CODE REVIEW

**Comment by egoist** [comment]
what `require` would you use for electron? it seems monaco only supports amd loader.

**Comment by hzjzx** [comment]
@egoist https://github.com/Microsoft/monaco-editor-samples/tree/master/sample-electron

**Comment by egoist** [comment]
Nice then, can you update the doc as well? 😄  https://github.com/egoist/vue-monaco#props

**Comment by egoist** [comment]
Nice, thanks for efforts

**Comment by jeeftor** [comment]
https://github.com/Microsoft/monaco-editor-samples/tree/master/sample-electron is no longer a valid link

**Pull request merged**
